#!/bin/bash

module purge
module load pbs
module load openmpi/1.8.5
module load esmf
# module use /g/data3/hh5/public/modules
# module load conda/analysis3

ln -s /g/data1/v45/aph502/jra55/sss/mean_salinity_of_0_and_10m.nc grid_in.nc
ln -s /short/v45/aph502/mom/input/mom01/mosaic/ocean_hgrid.nc grid_out.nc

# grd2scrip.py -v grid_in.nc
# grd2scrip.py -v grid_out.nc 

qsub regrid.pbs
