#!/bin/bash
#PBS -q express
#PBS -l ncpus=16
#PBS -l wd
#PBS -l walltime=4:00:00
#PBS -l mem=64GB
#PBS -l jobfs=512GB
#PBS -P v45

module purge
module load openmpi/1.8.5
module load esmf
module use /g/data3/hh5/public/modules
module load conda/analysis3

PATH=${PATH}:/short/v45/aph502/regrid/pyregrid

grd2scrip.py -v grid_in.nc
grd2scrip.py -v grid_out.nc

mpirun -np ${PBS_NCPUS} ESMF_RegridWeightGen -v --netcdf4 -m conserve -p none -s grid_in_scrip.nc -d grid_out_scrip.nc -w weights.nc 

